apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-apigateway
  labels:
    app: {{ .Release.Name }}
    app2: {{ .Release.Name }}-apigateway
spec:
  replicas: {{ int .Values.apigateway.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
      app2: {{ .Release.Name }}-apigateway
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
        app2: {{ .Release.Name }}-apigateway
    spec:
      containers:
        - env:
            - name: JAVA_OPTS
              value: -Dspring.profiles.active=docker -XX:MaxDirectMemorySize=500M -Xss256k
          image: {{ .Values.image.repository }}/api-gateway:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name:  apigateway
          ports:
            - containerPort: 8080
          {{- with .Values.apigateway.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            failureThreshold: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            failureThreshold: 10
            periodSeconds: 5
            timeoutSeconds: 10
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /home/appuser/app/config/application.yml
              subPath: apigateway.yml
              readOnly: false
            - name: {{ .Release.Name }}-configs
              mountPath: /home/appuser/app/config/bootstrap.yml
              subPath: apigateway-bootstrap.yml
              readOnly: false
      hostname:  apigateway
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configs
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secrets