apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apigateway
spec:
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: apigateway
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: wafront
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
status:
  loadBalancer: {}