apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-apigateway
spec:
  selector:
    app: {{ .Release.Name }}-apigateway
  ports:
    - name: apigateway
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
status:
  loadBalancer: {}