apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configs
data:
  apigateway.yml: |-
{{ .Files.Get "configs/apigateway.yml" | indent 4}}
  apigateway-bootstrap.yml: |-
{{ .Files.Get "configs/apigateway-bootstrap.yml" | indent 4}}
  wahttpconsumer.env: |-
{{ .Files.Get "configs/wahttpconsumer.env" | indent 4}}
  instance-service.env: |-
{{ .Files.Get "configs/instance-service.env" | indent 4}}
  user-service.env: |-
{{ .Files.Get "configs/user-service.env" | indent 4}}
  wacore.env: |-
{{ .Files.Get "configs/wacore.env" | indent 4}}
  wahttpqr.env: |-
{{ .Files.Get "configs/wahttpqr.env" | indent 4}}
  waproducer.env: |-
{{ .Files.Get "configs/waproducer.env" | indent 4}}
  wamedia.env: |-
{{ .Files.Get "configs/wamedia.env" | indent 4}}
  warming-service.env: |-
{{ .Files.Get "configs/warming-service.env" | indent 4}}
  webhooker.env: |-
{{ .Files.Get "configs/webhooker.env" | indent 4}}