apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-secrets
data:
  # can be generated via command kubectl create secret docker-registry <name> --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email> 
  # Base64 should ends with =
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoid2FkZXZraXQiLCJwYXNzd29yZCI6ImdocF9iajF4b29DV0kxVXQ5bjIwTzBYZDNSajJOeGdoYnowWmoza2giLCJlbWFpbCI6IndhZGV2a2l0QHdhZGV2a2l0LmNvbSIsImF1dGgiOiJkMkZrWlhacmFYUTZaMmh3WDJKcU1YaHZiME5YU1RGVmREbHVNakJQTUZoa00xSnFNazU0WjJoaWVqQmFhak5yYUE9PSJ9fX0=
type: kubernetes.io/dockerconfigjson