apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-secrets
data:
  # can be generated via command kubectl create secret docker-registry <name> --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email> 
  # Base64 should ends with =
  # example kubectl create secret docker-registry screener-docker-secrets --docker-server=ghcr.io --docker-username=solution8 --docker-password=ghp_fsfs --docker-email=mail@screener.com 
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7InVzZXJuYW1lIjoid2FkZXZraXQiLCJwYXNzd29yZCI6ImdocF82N0U0MmJVOGVrQlBzVWJkYWtUM2RqV2hscXJ2b0sydDU0UmkiLCJlbWFpbCI6Im1haWxAc2Rrd2EuY29tIiwiYXV0aCI6ImQyRmtaWFpyYVhRNloyaHdYelkzUlRReVlsVTRaV3RDVUhOVlltUmhhMVF6WkdwWGFHeHhjblp2U3pKME5UUlNhUT09In19fQ==
type: kubernetes.io/dockerconfigjson
