apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wafront-home
spec:
  selector:
    app: {{ .Release.Name }}-wafront-home
  ports:
    - name: wafront-home
      protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
status:
  loadBalancer: {}