apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wahttpqr
spec:
  selector:
    app: {{ .Release.Name }}-wahttpqr
  ports:
    - protocol: TCP
      port: 6003
      targetPort: 6003