apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wahttpconsumer
  labels:
    app: {{ .Release.Name }}-wahttpconsumer
spec:
  replicas: {{ int .Values.wahttpconsumer.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wahttpconsumer
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wahttpconsumer
    spec:
      containers:
        - env:
          - name: ACTIVE_PROFILE
            value: docker
          - name: RABBIT_URI
            value: amqp://{{ .Values.rabbitmq.auth.username }}:admin@{{ .Release.Name }}-{{ .Values.rabbitmq.nameOverride}}:5672
          image: {{ .Values.image.repository }}/webhook-http-api-consumer:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: wahttpconsumer
          ports:
            - containerPort: 7002
          {{- with .Values.wahttpconsumer.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 7002
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 7002
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/config/app.env
              subPath: wahttpconsumer.env
              readOnly: false
      hostname: wahttpconsumer
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configs
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secrets