apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wamedia
  labels:
    app: {{ .Release.Name }}-wamedia
spec:
  replicas: {{ int .Values.wamedia.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wamedia
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wamedia
    spec:
      containers:
        - env:
          - name: ACTIVE_PROFILE
            value: docker
          image: {{ .Values.image.repository }}/wamedia:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: wamedia
          ports:
            - containerPort: 4005
          {{- with .Values.wamedia.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 4005
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 4005
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/config/app.env
              subPath: wamedia.env
              readOnly: false
      hostname: wamedia
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configs
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secrets