server:
  port: 8080
  
management:
  endpoint.health.probes.enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

wahttpqr:
  enable: true
  apiUrl: http://sdkwa-wahttpqr:6003
  applyFor:
    - qr
    
waconsumer:
  enable: true
  apiUrl: http://sdkwa-wahttpconsumer:7002
  applyFor:
    - ReceiveNotification
    - DeleteNotification

wadeprecated:
  enable: true
  applyFor:
    - getDeviceInfo

quotas:
  enable: false
  apiUrl: http://sdkwa-quotas:4000
  apiUrl2: http://sdkwa-quotas-service:4000
  ignoreFor:
    - ^2204\d*$
    - ^3305\d*$
    - ^55\d{2}\d*$
    
wamedia:
  apiUrl: http://sdkwa-wamedia:4005
  applyFor:
    - UploadFile

wainstancesettings:
  applyFor:
    - SetSettings
    - GetSettings
    - SetSystemProxy
    
partners-method:
  applyFor:
    - CreateInstance
    - DeleteInstanceAccount
    - GetInstance
    - GetInstances
    
waproducer:
  enable: true
  apiUrl: http://sdkwa-waproducer:6004
  applyFor:
    - sendMessage
    - sendButtons
    - sendTemplateButtons
    - sendListMessage
    - sendLocation
    - sendLink
    - sendContact
    - sendFileByUrl
    - clearMessagesQueue
    - showMessagesQueue
    - sendTemplate
    - forwardMessages

wbot-warming:
  enable: true
  apiUrl: http://sdkwa-warmingservice:7040
  applyFor:
    - getWarmingPhoneStatus

instance-service:
  apiUrl: http://sdkwa-instance-service:7020

user-service:
  apiUrl: http://sdkwa-user-service:7010

wacore:
  allowedMethods:
    - getSettings
    - setSettings
    - setSystemProxy
    - getStateInstance
    - getStatusInstance
    - reboot
    - logout
    - qr
    - scanQrCode
    - setProfilePicture
    - setProfileName
    - setProfileStatus
    - sendFileByUpload
    - uploadFile
    - receiveNotification
    - deleteNotification
    - downloadFile
    - getChatHistory
    - getChatHistoryCount
    - getMessage
    - lastIncomingMessages
    - lastOutgoingMessages
    - createGroup
    - updateGroupName
    - getGroupData
    - addGroupParticipant
    - removeGroupParticipant
    - setGroupAdmin
    - removeAdmin
    - setGroupPicture
    - leaveGroup
    - readChat
    - getDeviceInfo
    - checkWhatsapp
    - getAvatar
    - getAvatarAsync
    - getContacts
    - getContactInfo
    - deleteMessage
    - archiveChat
    - unarchiveChat
    - setDisappearingChat
    - setSettings
    - getWaSettings
    - getChats
    - getChatsCount
    - setSystemProxy
    - requestRegistrationCode
    - sendRegistrationCode

limits:
  swcoreMaxBodySizeMB: 100
  othersMaxBodySizeMB: 10
  requestMaxHeaderSizeKB: 8092
  wamediaoutMaxBodySizeMB: 100
  requestDefaultRateLimit: 50
  enableBurstCapacity: false
  rates:
    getSettings: 1
    setSettings: 1
    setSystemProxy: 1
    getStateInstance: 5
    getStatusInstance: 5
    reboot: 1
    logout: 1
    qr: 3
    scanQrCode: 1
    setProfilePicture: 1
    sendFileByUpload: 5
    receiveNotification: 100
    deleteNotification: 100
    downloadFile: 5
    getChatHistory: 1
    getMessage: 10
    lastIncomingMessages: 1
    lastOutgoingMessages: 1
    createGroup: 1
    updateGroupName: 1
    getGroupData: 1
    addGroupParticipant: 10
    removeGroupParticipant: 10
    setGroupAdmin: 10
    removeAdmin: 10
    setGroupPicture: 1
    leaveGroup: 10
    readChat: 10
    getDeviceInfo: 1
    checkWhatsapp: 10
    getAvatar: 10
    getAvatarAsync: 10
    getContacts: 1
    getContactInfo: 1
    deleteMessage: 10
    archiveChat: 10
    unarchiveChat: 10
    setDisappearingChat: 1
    getWaSettings: 1
    getChats: 1
    sendMessage: 50
    sendButtons: 50
    sendTemplateButtons: 50
    sendListMessage: 50
    sendLocation: 50
    sendLink: 50
    sendContact: 50
    sendFileByUrl: 50
    clearMessagesQueue: 1
    showMessagesQueue: 1
    sendTemplate: 50
    forwardMessages: 50
    sendRegistrationCode: 1
    requestRegistrationCode: 1

auth:
  enable: true
  host: http://sdkwa-instance-service:7020
  authorization: obsoleted

spring:
  cloud:
    gateway:
      routes:
        - id: main_page
          uri: http://sdkwa-apigateway:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
            - GET
            - POST
            - DELETE
            - PUT
      filter:
        request-rate-limiter:
          enabled: false


  redis:
    database: 0
    host: localhost
    password: changeit
    port: 6379
    timeout: 60000

logging:
  level:
    org.springframework.cloud.gateway: WARN
    reactor.netty: WARN
    org.apache.http.client: WARN
    org.springframework.web.client: WARN
    org.sdkwa.apigateway: DEBUG
    
web:
  httpTimeoutMs: 30000