apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-instance-service
spec:
  selector:
    app: {{ .Release.Name }}-instance-service
  ports:
    - protocol: TCP
      port: 7020
      targetPort: 7020