{{- if .Values.instanceservice.hpa.enabled -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-instance-service
  labels:
    app: {{ .Release.Name }}
spec:
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: {{ .Release.Name }}-instance-service
  minReplicas: {{ .Values.instanceservice.hpa.minpods }}
  maxReplicas: {{ .Values.instanceservice.hpa.maxpods }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.instanceservice.hpa.cputhreshold }}
  {{- end }}
