apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  mysql-password: YWRtaW4=
  mysql-root-password: YWRtaW4=
  mysql-replication-password: YWRtaW4=
  rabbitmq-password: YWRtaW4=
