apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-user-service
spec:
  selector:
    app: {{ .Release.Name }}-user-service
  ports:
    - protocol: TCP
      port: 7010
      targetPort: 7010