apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wahttpconsumer
spec:
  selector:
    app: {{ .Release.Name }}-wahttpconsumer
  ports:
    - protocol: TCP
      port: 7002
      targetPort: 7002