apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wahttpqr
  labels:
    app: {{ .Release.Name }}-wahttpqr
spec:
  replicas: {{ int .Values.wahttpqr.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-wahttpqr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-wahttpqr
    spec:
      containers:
        - env:
          - name: ACTIVE_PROFILE
            value: docker
          image: {{ .Values.image.repository }}/wahttpqr:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: wahttpqr
          ports:
            - containerPort: 6003
          {{- with .Values.wahttpqr.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 6003
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 6003
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/config/app.env
              subPath: wahttpqr.env
              readOnly: false
      hostname: wahttpqr
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configs
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secrets