apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-warmingservice
  labels:
    app: {{ .Release.Name }}-warmingservice
spec:
  replicas: {{ int .Values.warmingservice.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-warmingservice
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-warmingservice
    spec:
      containers:
        - env:
          - name: ACTIVE_PROFILE
            value: docker
          image: {{ .Values.image.repository }}/warming-service:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: warmingservice
          ports:
            - containerPort: 7040
          {{- with .Values.warmingservice.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 7040
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 7040
            initialDelaySeconds: 60
            failureThreshold: 3
            periodSeconds: 3
          volumeMounts:
            - name: {{ .Release.Name }}-configs
              mountPath: /usr/src/app/config/app.env
              subPath: warming-service.env
              readOnly: false
      hostname: warmingservice
      volumes:
        - name: {{ .Release.Name }}-configs
          configMap:
            name: {{ .Release.Name }}-configs
      restartPolicy: Always
      imagePullSecrets:
        - name: {{ .Release.Name }}-docker-secrets