apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-warmingservice
spec:
  selector:
    app: {{ .Release.Name }}-warmingservice
  ports:
    - protocol: TCP
      port: 7040
      targetPort: 7040